website:
  title_separator: "|"
  debug: false
  truncate: 255
  release_year: "2017"

theme:
  name: ""
  link: ""
  integrity: ""

gravatar:
  size: 20
  rating: "g"
  default_image: ""
  force_default_image: false
  secure_request: true
